### ISSUE TITLE
Setup a React JS project with create-react-app and install tailwind CSS

### ISSUE THREAD

**Issue by shashank-iter** [CareerDevelopmentHub/ticket.raise#4]
- Tailwind CSS should be activated on all the JSX and TSX files in the `/src` directory.

**Comment by k0msenapati** [comment]
I can work on this issue.

**Comment by k0msenapati** [comment]
I want to know where to set up the project in a subfolder or ticket.raise folder.

**Comment by shashank-iter** [comment]
> I want to know where to set up the project in a subfolder or ticket.raise folder.

Set up the project in the ticket.raise folder and there would be two HTML files that were merged previously, if you can convert them to JSX and put in the /src folder in react setup, that would be amazing.

**Comment by shashank-iter** [comment]
> I can work on this issue.

You can start working on this issue. Will officially assign you shortly, don't have access to PC right now.
